//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonToUAsset {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.9.0.0")]
    internal sealed partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettings defaultInstance = ((UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings())));
        
        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BaseFilesLocation {
            get {
                return ((string)(this["BaseFilesLocation"]));
            }
            set {
                this["BaseFilesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Terrain_DigSize {
            get {
                return ((string)(this["Terrain_DigSize"]));
            }
            set {
                this["Terrain_DigSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Minerals_DigSize {
            get {
                return ((string)(this["Minerals_DigSize"]));
            }
            set {
                this["Minerals_DigSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MineralsAndTerrain_DigSize {
            get {
                return ((string)(this["MineralsAndTerrain_DigSize"]));
            }
            set {
                this["MineralsAndTerrain_DigSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Terrain_OneHit {
            get {
                return ((string)(this["Terrain_OneHit"]));
            }
            set {
                this["Terrain_OneHit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Minerals_OneHit {
            get {
                return ((string)(this["Minerals_OneHit"]));
            }
            set {
                this["Minerals_OneHit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MineralsAndTerrain_OneHit {
            get {
                return ((string)(this["MineralsAndTerrain_OneHit"]));
            }
            set {
                this["MineralsAndTerrain_OneHit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Terrain_DigSize_OneHit {
            get {
                return ((string)(this["Terrain_DigSize_OneHit"]));
            }
            set {
                this["Terrain_DigSize_OneHit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Minerals_DigSize_OneHit {
            get {
                return ((string)(this["Minerals_DigSize_OneHit"]));
            }
            set {
                this["Minerals_DigSize_OneHit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MineralsAndTerrain_DigSize_OneHit {
            get {
                return ((string)(this["MineralsAndTerrain_DigSize_OneHit"]));
            }
            set {
                this["MineralsAndTerrain_DigSize_OneHit"] = value;
            }
        }
    }
}
